### ISSUE TITLE
After launching the shortcut app on iPad, only notifications will be displayed

### ISSUE THREAD

**Issue by appleiPodTouch4** [nythepegasus/SideJITServer#103]
![image](https://github.com/user-attachments/assets/44764918-b5ad-407b-a282-c894061a9503)
![IMG_0107](https://github.com/user-attachments/assets/8a79a562-e402-41a1-8bee-54a608608670)

**Comment by appleiPodTouch4** [comment]
and i use the M4 ipadpro

**Comment by Supergrafiti** [comment]
I had the same one. It just sees only those applications that are signed by the developer's certificate, and others are not (I don't know much, but I think there is some kind of filter). When I signed through the developer's certificate, this application was visible

**Comment by appleiPodTouch4** [comment]
Before this, I used the corporate signature

**Comment by nythepegasus** [comment]
I hope this is solved, if not reopen.

**Comment by SuperGamer747** [comment]
How do you fix it?
I'm usingappdb.
