### ISSUE TITLE
Run apps without developer certificate

### ISSUE THREAD

**Issue by Supergrafiti** [nythepegasus/SideJITServer#105]
Is there a way to run applications that are not signed with a developer certificate? Because they just don't appear in the selection of applications to run with jit

**Comment by 0hStormy** [comment]
iirc you need a developer certificate for JIT "debugging"

**Comment by nythepegasus** [comment]
It must allow `get-task-allow` otherwise it will not appear in the list. Limitation imposed by Apple.
