### ISSUE TITLE
{"ERROR":"Could not find device!"}

### ISSUE THREAD

**Issue by Phoebruary** [nythepegasus/SideJITServer#108]
I've followed the instructions and everything worked up until I opened the SideJIT shortcut for the first time. I entered everything correctly to set it up but I'm getting a "could not find device" error. 

Is there any way to fix this?

**Comment by nythepegasus** [comment]
Could you try the newest version? Also I will try and consolidate all the `{"ERROR": "Could not find device!"}` issues into a single issue for better tracking. #111
