### ISSUE TITLE
Help

### ISSUE THREAD

**Issue by Elbozo123** [nythepegasus/SideJITServer#11]
Im trying to setup the shortcut so which ip do I use?

![image](https://github.com/nythepegasus/SideJITServer/assets/122303564/112dafa2-4515-4bdd-bea1-cd9208af1abd)

**Comment by WesleyBryie** [comment]
Use the LAN IP (in this case it would be 192.168.1.59).

**Comment by Montivillon** [comment]
The second one, the first one will be used to refresh after you used JIT or if JIT not working

**Comment by Elbozo123** [comment]
I tried it so many times but the shortcut kept saying { Error: no device found} even though there was response from my computer

**Comment by Montivillon** [comment]
www.127.0.0.1:8080/re/

**Comment by Montivillon** [comment]
Btw I also had the error message. I clicked the link and had another error message. If this happens, delete the shortcut and reset it up, and it worked go try
