### ISSUE TITLE
Internal Server Error for PojavLauncher

### ISSUE THREAD

**Issue by Unknown1234029** [nythepegasus/SideJITServer#110]
File "C:\Users\iamar\AppData\Local\Programs\Python\Python312\Lib\site-packages\pymobiledevice3\remote\remote_service_discovery.py", line 112, in get_service_port
    raise InvalidServiceError(f'No such service: {name}')
pymobiledevice3.exceptions.InvalidServiceError: No such service: com.apple.instruments.dtservicehub
INFO:werkzeug:192.168.68.89 - - [17/Aug/2024 11:25:05] "GET /00008101-000D25D934E1001E/PojavLauncher/ HTTP/1.1" 500 -

This is the error I'm getting while trying to enable JIT for PojavLauncher
![IMG_1143](https://github.com/user-attachments/assets/2bc0318a-6eb9-41c4-81bc-198f5bb291ae)

**Comment by nythepegasus** [comment]
Try using the current latest version, also make sure you're running as admin
