### ISSUE TITLE
wrong uvicorn address?

### ISSUE THREAD

**Issue by frootloop88** [nythepegasus/SideJITServer#121]
it says INFO:     Uvicorn running on http://127.0.0.1:49151

but shouldn't it show my local IP address? What can I do?

it doesn't go any further than this:

INFO:     Started server process [770]
INFO:     Waiting for application startup.
INFO:     Application startup complete.
INFO:     Uvicorn running on http://127.0.0.1:49151 (Press CTRL+C to quit)

**Comment by frootloop88** [comment]
I completely wiped my Mac and iPhone to latest official versions and it still stuck there

**Comment by frootloop88** [comment]
If I only useSideJITServer it seems to run the server but when I press the shortcut I get "device not found" and if I use it with SideJITServer --pair its just stuck

**Comment by itzTheMeow** [comment]
i'm using this same issue, stuck on the UDID step

**Comment by thelocalmangaka** [comment]
Same issue here

**Comment by frootloop88** [comment]
Got it to work with sudo SideJITServer —pair

**Comment by ileeric** [comment]
Same error here

**Comment by ThatKoza** [comment]
same issue

**Comment by ThatSirWaffles** [comment]
> Got it to work with sudo SideJITServer —pair

This seems to be working fine on mac! You can then do the rest as the documentation states. You can grab your local IP from your internet settings, then get your UDID from 192.168.x.x:8080, and use that same address with port 8080 in the shortcut.
