### ISSUE TITLE
pymobiledevice3.exceptions.MuxException: got an error message

### ISSUE THREAD

**Issue by tenshi0xx** [nythepegasus/SideJITServer#142]
![image](https://github.com/user-attachments/assets/72f47db1-e5db-44c6-a3fc-b94cb23b1168)

This happen when i tried to do ```SideJITServer --pair`` with my iPhone 15 Pro - iOS 18.1 Developer Beta 5.

**Comment by Ra2-IFV** [comment]
Full logs?
Also try plug in you device again?

**Comment by tenshi0xx** [comment]
> Full logs? Also try plug in you device again?

Hello. I fixed this issue long ago, thanks for your concern!

I use 3utools to sync the device again and bind the device with iTunes and it works.
