### ISSUE TITLE
Reques timed out

### ISSUE THREAD

**Issue by DelayedHappiness** [nythepegasus/SideJITServer#18]
![image](https://github.com/nythepegasus/SideJITServer/assets/91527381/059a4177-e23e-4589-baa1-65687c9d8ab8)

I get that message whenever I try to use the sidejit shortcut. I've done everything according to guides, got my UDID and Server address but the shortcut asks for permission to connect to Brave and not the address like in other people's videos then says request timed out. Any idea why this may be? Everything else is okay and my phone is detected by the server on power shell

**Comment by DelayedHappiness** [comment]
I'd like to also say that the pop up for allowing networks to use the app I accidentally said no while doing the whole process and it never appeared again, I've tried to make it appear again but to no avail either. that may be the issue but I cant replicate so I'm not really sure

**Comment by Exe008** [comment]
For me it happens exactly the same despite allowing access to the network when I was prompted.

**Comment by Exe008** [comment]
Just now I found what fixed it for me: I had to allow python through the firewall on the PC, now it seems to be working for me.

(on another note, DolphinIOS v3.2.1 then crashed to homescreen when trying to open any games, switching to public beta v4.0.0b7 fixed the crash - now both JIT and DolphinIOS(beta) are working)

**Comment by DelayedHappiness** [comment]
And how do I exactly allow purging through the firewall? I tried getting it to send the prompt asking for permission but nothing worked so far

**Comment by Exe008** [comment]
In the Windows Start menu, 
> search for "Allow an App through Windows Firewall" 
> click on "Change settings" (requires administator rights) 
> scroll down the list and make sure whatever Python you use is allowed to pass through as indicated by the checkboxes

**Comment by DelayedHappiness** [comment]
That solved the issue! Thank you @Exe008 for the knowledge.
