### ISSUE TITLE
Shortcut issue

### ISSUE THREAD

**Issue by Checkm8ra1n** [nythepegasus/SideJITServer#2]
![Screenshot 2024-03-27 185519](https://github.com/nythepegasus/SideJITServer/assets/110713827/fd1d24b2-00d4-416e-ab70-b8282257f934)
![IMG_2022](https://github.com/nythepegasus/SideJITServer/assets/110713827/fb003b1b-b993-419d-bbb2-f7cfcd6c6dfc)
![IMG_2021](https://github.com/nythepegasus/SideJITServer/assets/110713827/cc3c87c0-7825-495f-9ccd-b9b98d479b80)

**Comment by nythepegasus** [comment]
Hello, could you try the newest version?

**Comment by not-nullptr** [comment]
> Hello, could you try the newest version?

just tried, same bug

**Comment by WesleyBryie** [comment]
@not-nullptr Could you please try going to http://<ip>:8080/00008101-000C14363E88001E/ where <ip> is either localhost or your computers IP address, in a browser and share the output please?

**Comment by not-nullptr** [comment]
@WesleyBryie gives "could not find device" . this is the same error i get with my actual ID too

**Comment by WesleyBryie** [comment]
> @WesleyBryie gives "could not find device" . this is the same error i get with my actual ID too 

I typed out your actual ID. Is the tunnel detecting your device? It should be a string with either wifi or usb in it.

**Comment by not-nullptr** [comment]
@WesleyBryie that isn't my ID, i'm a different person . it doesn't detect it , that's whats causing the error

**Comment by WesleyBryie** [comment]
> @WesleyBryie that isn't my ID, i'm a different person . it doesn't detect it , that's whats causing the error

Myb. I'll let ny figure this out.

**Comment by NinjaCheetah** [comment]
Also having the same issue. Going to the URL of my device's UDID also just returns "Device not found!".

**Comment by WesleyBryie** [comment]
> Also having the same issue. Going to the URL of my device's UDID also just returns "Device not found!". Server is running on Linux in my case, if that makes any difference.

I remember @nythepegasus mentioned that linux probably needs a kernel patch for this to work...

**Comment by tannerellen** [comment]
I got this error before. To fix it I physically plugged my iPad into my computer. Then I visited the following url from my iPad: http://yourip:8080/re
replacing "yourip" with my computer's IP address. Then I ran the SideJIT shortcut to start JIT. After that I unplugged my iPad from my computer and everything has worked great ever since. This was on a mac so your mileage may vary on other platforms.

**Comment by WesleyBryie** [comment]
Was this closed because your issue was solved or because of the new PyPI package?

For future reference, running `pip3 install SideJITServer` now will install a SideJITServer.exe on your machine

Wesley Bryie

***@***.***
***@***.***

https://wesbryie.com/
________________________________
