### ISSUE TITLE
Rich Text to URL Conversion failed for Shortcuts

### ISSUE THREAD

**Issue by VulDee** [nythepegasus/SideJITServer#22]
So I wanted to try out SideJIT since I can't access it in SideStore and I wanted to play nintendo switch roms with sudachi, but when I try to open the shortcut I keep getting this error saying "Get Contents of URL failed Shortcuts couldn't convert from Rich text to URL". Tried to find a solution in some Megathreads of Reddit but no dice, please help me thank you.

**Comment by stossy11** [comment]
1. did you compile Folium x Sudachi from source 
2. make sure you put http:// and :8080 in the url

**Comment by VulDee** [comment]
The https:// helped thank you very much, but i have another qwuestion, can I use SideJITServer without my mac open?

**Comment by stossy11** [comment]
No but also it should be http:// not https://

**Comment by VulDee** [comment]
Sad that apple made JIT not available natively, thanks for the help. cheers.

**Comment by VulDee** [comment]
Sorry new problem, where do I find my udid of my iphone on my mac?

**Comment by WesleyBryie** [comment]
iTunes or one of the many UDID finders

Wesley Bryie

***@***.***
***@***.***

https://wesbryie.com/
________________________________

**Comment by VulDee** [comment]
I used https://udid.tech but it keeps saying device not found in the shortcut.

**Comment by stossy11** [comment]
go to the sidejitserver ip that you put into shortcut in your web browser and your udid should be there

**Comment by SkylineUset** [comment]
i forgor
