### ISSUE TITLE
Missing module even though I installed the module

### ISSUE THREAD

**Issue by 0hStormy** [nythepegasus/SideJITServer#23]
![image](https://github.com/nythepegasus/SideJITServer/assets/80485413/504387a7-29f5-46e5-ae39-0a8a416f96e3)

**Comment by WesleyBryie** [comment]
Run `pip3 install -r requirements.txt` if you have that file

Wesley Bryie

***@***.***
***@***.***

https://wesbryie.com/
________________________________
From: Stormy ***@***.***>
Sent: Wednesday, April 24, 2024 9:54:51 PM
To: nythepegasus/SideJITServer ***@***.***>
Cc: Subscribed ***@***.***>
Subject: [nythepegasus/SideJITServer] Missing module even though I installed the module (Issue #23)


image.png (view on web)<https://github.com/nythepegasus/SideJITServer/assets/80485413/504387a7-29f5-46e5-ae39-0a8a416f96e3>

**Comment by 0hStormy** [comment]
Did that and I get the same module error.
(I'm on Fedora 40 if you need more info)

**Comment by takov751** [comment]
@0hStormy you have installed the modules as your user so your root does not have access to it. to make it easier and bit less messy i would recommend using venv.

```
# create virtualenv
python3 -m venv $HOME/anywhere/.venv
# enter into the virtual environment and install whatever you would like
source $HOME/anywhere/.venv/bin/activate
(.venv) $ pip3 install -r requirements.txt

# run command as root with sudo
sudo $HOME/anywhere/.venv/bin/python3 -m SideJITServer --help
```

**Comment by 0hStormy** [comment]
Got it to work, I just had to use pip with sudo while in venv
