### ISSUE TITLE
Conversion Error: Get Dictionary from Input failed because Shortcuts couldn't convert from Rich Text to Dictionary.

### ISSUE THREAD

**Issue by Majorical** [nythepegasus/SideJITServer#26]
I've no idea how to fix this and I've searched the Discord and these issue threads and I've got nothing.
![IMG_0432](https://github.com/nythepegasus/SideJITServer/assets/71177057/66657f56-8f62-4aaf-85d2-1c4c2b2385ea)

**Comment by Jose10Espinoza** [comment]
Make sure your UDID is correct and the server ip looks something like this http://ipadress:8080

**Comment by Wye34731** [comment]
I know this was two weeks ago but I have a problem that is the same as this one.
I enter my IP address EXACTLY like this: http://(ipaddress):8080 but it still says it couldn't convert Rich text to Dictionary.
