### ISSUE TITLE
Internal error

### ISSUE THREAD

**Issue by Montivillon** [nythepegasus/SideJITServer#28]
![IMG_0199](https://github.com/nythepegasus/SideJITServer/assets/156731526/ec723cea-4b80-45af-aaaf-9423523638f2)
I can’t enable JIT because of this issue which I am REALLY not familiar of and I have no idea how to solve it so I need help.

**Comment by stossy11** [comment]
Can you show what SideJITServer says not the shortcut

**Comment by Montivillon** [comment]
![Uploading IMG_0218.jpeg…]()

**Comment by ScoutAndAbout** [comment]
same problem here

**Comment by takov751** [comment]
We would need more info what's going on SideJITServer side where it's running. This message is not really helpful on it's own

**Comment by wanderer-fly** [comment]
`pip install pymobiledevice3==4.2.3` helps for me

**Comment by lunarnaut3** [comment]
wanderer fly u just helped me out ty so much

**Comment by Hky-Des** [comment]
same problem here +1

**Comment by harryxhk** [comment]
same problem.
