### ISSUE TITLE
 WARNING failed to connect to usbmux. waiting for it to restart

### ISSUE THREAD

**Issue by danysgit** [nythepegasus/SideJITServer#32]
WARNING failed to connect to usbmux. waiting for it to restart
![2024-04-27 01_24_26-Saved Messages](https://github.com/nythepegasus/SideJITServer/assets/22780711/76be9150-aecd-4112-a441-30d971154d7c)

**Comment by WesleyBryie** [comment]
Try restarting your computer and trying SideJITServer again.

**Comment by danysgit** [comment]
Problem persists after reboot
![2024-04-27 15_18_36-](https://github.com/nythepegasus/SideJITServer/assets/22780711/a259e34e-d113-4917-a01f-e8338dc07a04)

**Comment by not-nullptr** [comment]
same issue here.

**Comment by oyoyjun** [comment]
同样的问题

**Comment by nythepegasus** [comment]
Could you try the newest version as well as make sure you have an updated usbmuxd implementation installed?
