### ISSUE TITLE
IOS 17.5 The Shortcut has timed out/MacOS Bad file descriptor 

### ISSUE THREAD

**Issue by BIGMIKE1212** [nythepegasus/SideJITServer#39]
So I got the shortcut to work once and now I try it and it keeps on timing out so I plugged my phone into my Mac and it says bad file descriptor when I try to activate the shortcut what is wrong and can I get some help to fix it.![image](https://github.com/nythepegasus/SideJITServer/assets/169582757/6ca041e6-e579-4b1f-82fc-d61ecaaf7721)

**Comment by WesleyBryie** [comment]
Would you mind sharing how you fixed this issue for future reference?

**Comment by BIGMIKE1212** [comment]
So each time the shortcut stops working you would have to manually redo the terminal or power shell depending on what computer you use
