### ISSUE TITLE
`pip3 install SideJITStore` returns error

### ISSUE THREAD

**Issue by vinhtq115** [nythepegasus/SideJITServer#42]
When running `pip3 install SideJITStore` command according to the README.md file, I encountered this error:

```
ERROR: Could not find a version that satisfies the requirement SideJITStore (from versions: none)
ERROR: No matching distribution found for SideJITStore
```

I tried to find the package on pypi and it seems that the package does not exist at all.

**Comment by don17sch** [comment]
try pip3 install SideJITServer

**Comment by vinhtq115** [comment]
> try pip3 install SideJITServer

This one works. Thank you.
