### ISSUE TITLE
The shortcuts issues

### ISSUE THREAD

**Issue by LO-FANG** [nythepegasus/SideJITServer#44]
the shortcuts just show a Notification ,then it's over, didn't show the app list. And the PC show ""GET /myUDID/ HTTP/1.1" 200 -"
IOS 17.5
windows 11

![pic](https://github.com/nythepegasus/SideJITServer/assets/20740475/9249bdee-d75d-4e82-969d-dce39f3ac718)

**Comment by Bomen9** [comment]
@LO-FANG What did you do to solve your issue? We #61 need to know.

**Comment by LO-FANG** [comment]
> @LO-FANG What did you do to solve your issue? We #61 need to know.

As all I konw, make sure using the AltStore or SideStore to sidestore your app
