### ISSUE TITLE
Error when running `pip install SideJITServer`

### ISSUE THREAD

**Issue by TechnicallyJackson** [nythepegasus/SideJITServer#45]
This is not #42 
When I run (in venv) the actual command `pip install SideJITServer` or `pip3 install SideJITServer`
I get in return `ERROR: Could not find a version that satisfies the requirement SideJITServer (from versions: none)`
`ERROR: No matching distribution found for SideJITServer`

**Comment by takov751** [comment]
without context I would recommend checking your python version and pip version as sidejitserver only compatible with python3.11 or newer

**Comment by XalexGithub** [comment]
I'm on python 3.11.9, same error message.

**Comment by LifeDreamer24** [comment]
![image](https://github.com/nythepegasus/SideJITServer/assets/62817314/510edea1-e6b4-452b-8ce8-cb8ccd787a4c)
same here, everything works until this step.

**Comment by LifeDreamer24** [comment]
im using 3.12

**Comment by TechnicallyJackson** [comment]
> im using 3.12

You are using `pip install SideJITStore` not `pip install SideJITServer`
Use store instead of server in SideJITServer
This might be the problem

**Comment by LifeDreamer24** [comment]
found out but later on i got this:
![image](https://github.com/nythepegasus/SideJITServer/assets/62817314/0b43e840-21d1-41b6-b96d-c4d24d4cb8f1)

**Comment by TechnicallyJackson** [comment]
> found out but later on i got this: ![image](https://private-user-images.githubusercontent.com/62817314/331907226-0b43e840-21d1-41b6-b96d-c4d24d4cb8f1.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTYxNjA1ODIsIm5iZiI6MTcxNjE2MDI4MiwicGF0aCI6Ii82MjgxNzMxNC8zMzE5MDcyMjYtMGI0M2U4NDAtMjFkMS00MWI2LWI5NmQtYzRkMjRkNGNiOGYxLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA1MTklMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNTE5VDIzMTEyMlomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPThkM2M3ODljMjc3NTBmNGVmNzk2ZWVlZTYwOTUyZWU4ZTcwM2Q0MDc4NGFiYzc4YmY3YWM0YmJmMzM1OTIyZGUmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.52y9-f1KMkujpkTZfN6JVUOBKW-WAvEgUiCyvfXzKBQ)

I recommend you open up a new issue

**Comment by GottaLoveAng** [comment]
I switched to my Arch Linux installation with Python 3.11.8 and still received the same `"ERROR: Could not find a version that satisfies the requirement SideJITServer (from versions: none)"` despite following the same steps. Seems like the problem is platform-agnostic.

**Comment by HarukaB** [comment]
use ```pip install SideJITServer``` instead

**Comment by HarukaB** [comment]
> found out but later on i got this: ![image](https://private-user-images.githubusercontent.com/62817314/331907226-0b43e840-21d1-41b6-b96d-c4d24d4cb8f1.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTYyOTkwMDUsIm5iZiI6MTcxNjI5ODcwNSwicGF0aCI6Ii82MjgxNzMxNC8zMzE5MDcyMjYtMGI0M2U4NDAtMjFkMS00MWI2LWI5NmQtYzRkMjRkNGNiOGYxLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA1MjElMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNTIxVDEzMzgyNVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTljM2U4YWQ4ODUwZGFmNWFjNDY0YzRjMjk4NzFmNmI0ZDgwMTU5ZWNmMDllMTE0YzY1YTExNDgyZjRlMTFhZjAmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.rWfx1CRbjsISgnOad53OoHKbNiITVGrnUMWPsWQSp7Q)

make sure you installed all required packages by running ```pip install -r requirements.txt```

**Comment by GottaLoveAng** [comment]
> use ```pip install SideJITServer``` instead

I used both pip3 and pip and got the same results. The user that created this issue also mentioned they've done this with no different results.

**Comment by HarukaB** [comment]
> > use `pip install SideJITServer` instead
> 
> I used both pip3 and pip and got the same results. The user that created this issue also mentioned they've done this with no different results.

maybe try to upgrade pip? use ```python -m pip install --upgrade pip```

**Comment by GottaLoveAng** [comment]
I guess I was typing it as "SideJITStore," I tried running the command and noticed that my command said store instead of server. It worked after fixing it.

**Comment by CodeSearcher59** [comment]
I had this issue at first, but it resolved after installing the windows store version of 3.11. However, the help command did not work after it completed the installation, showing this error:
SideJITServer : The term 'SideJITServer' is not recognized as the name of a cmdlet, function, script file, or operable
program. Check the spelling of the name, or if a path was included, verify that the path is correct and try again.
At line:1 char:1
+ SideJITServer --help
+ ~~~~~~~~~~~~~
    + CategoryInfo          : ObjectNotFound: (SideJITServer:String) [], CommandNotFoundException
    + FullyQualifiedErrorId : CommandNotFoundException

**Comment by DiFuks** [comment]
`pip3.11 install SideJITServer` worked for me

For some reason, the version inside venv differs from the one outside of it. Specifying the version explicitly helps.


![Снимок экрана 2024-07-24 в 23 09 53](https://github.com/user-attachments/assets/667c3f9b-aab1-4641-8ad7-c997a7fc0e5f)

**Comment by nythepegasus** [comment]
It is not SideJITStore, it is SideJITServer. 1.3.3 also lowered the requirement down to 3.9, but it definitely needs testing.
