### ISSUE TITLE
Pairing device with SideJITServer breaks SideStore pairing

### ISSUE THREAD

**Issue by SudoPigeon223** [nythepegasus/SideJITServer#46]
After running SideJITServer —pair and SideJITServer -d, SideStore no longer works unless the pairing file for SideStore is reset and added again using jitterbug and a computer.

**Comment by nythepegasus** [comment]
Hmm the pairing file should be in ~/.pymobiledevice3 if you want to copy the same one pymd3 generates for SideStore.
