### ISSUE TITLE
Shortcut breaks on having a space in either the URL or UDID fields at the end of the values

### ISSUE THREAD

**Issue by ChrisVanderHill** [nythepegasus/SideJITServer#49]
As said above having a space at the end of either fields causes the shortcut to just output the udids instead of the app list. Figured this out in the discord with @WesleyBryie and @Fishodee
discord thread:https://discord.com/channels/949183273383395328/1242316611973681162

**Comment by stossy11** [comment]
thats an iOS shortcut issue

**Comment by stossy11** [comment]
I will make a check for that so thanks for making this

**Comment by ChrisVanderHill** [comment]
> I will make a check for that so thanks for making this

Great, there was already a rudimentary fix made by Fishodee in the discord thread I linked, possibly you can use that

**Comment by stossy11** [comment]
I have made a fix now im just waiting on nythepegasus

**Comment by originalfapster** [comment]
What was the fix? That discord link does not open for me

**Comment by nythepegasus** [comment]
@stossy11 I can link the fix if you have a PR for it, closing for now in the hope you do.
