### ISSUE TITLE
After Connection pair no ip address shows but 127.0.0.1

### ISSUE THREAD

**Issue by ZenoRewn** [nythepegasus/SideJITServer#51]
Hi there,

I had follow all the steps.
And the `$ SideJITServer --version` can output the version info correctly.
But when I execute the `SideJITServer --pair`. It only shows the localhost ip address.
Can someone help with?

My device is M4 ipad and running the script on Mac with Python 3.11.

```
r$ SideJITServer --pair
Attempting to pair to a device! (Ctrl+C to stop)
[<PlistUsbmuxLockdownClient ID:xxx-xxx VERSION:17.5.1 TYPE:iPad16,6 PAIRED:True>]
Continue? [y/N]: y
INFO:     Started server process [42768]
INFO:     Waiting for application startup.
INFO:     Application startup complete.
INFO:     Uvicorn running on http://127.0.0.1:49151 (Press CTRL+C to quit)
```

**Comment by kayg04** [comment]
yeah, same here

**Comment by artchsh** [comment]
For me, it too shows only localhost ip address. You can get your local ip in wifi settings. 
For mac os it will be in WIFI settings
<img width="493" alt="image" src="https://github.com/nythepegasus/SideJITServer/assets/103406690/ea5615d3-c17d-4c02-941f-68868e793e9c">
For Windows/Linux you can look it up in Google "how to find local ip address windows 10"

**Comment by zengbo** [comment]
You must use root user to start the program:
`sudo SideJITServer --pair`

**Comment by nythepegasus** [comment]
Make sure you're root, and don't pass `--pair`. Also try the latest version currently
