### ISSUE TITLE
Errno 1 in pymobiledevice due to insufficient permissions.

### ISSUE THREAD

**Issue by bwug** [nythepegasus/SideJITServer#52]
## Version info:
- OS: Linux Mint
- Python3: 3.11 Default
- SideJITServer: Current
- PyMobileDevice: 4.2.3
- iOS: 17.4

## Issue:
In pymobiledevice3/remote/tunnel_service.py, line 177 in start_tunnel
`self.tun = TunTapDevice()`
Leads to
`pytun.Error: [Errno 1] Operation not permitted`
I assume this is a sudo issue, however running `sudo SideJitServer --pair` results in a command-line error

**Comment by bwug** [comment]
# Note
After reading into it more, it seems to be an issue with how iOS 17+ handles USB connections, changes implemented during the 16->17 updates have conflicted with Linux's USB drivers, I cannot find a solution myself and would suggest others who found this to use windows.

**Comment by bucyumaaaaaa** [comment]
You can try "sudo path/to/venv/bin/SideJITServer --pair"
