### ISSUE TITLE
Could not find 'UTM'!

### ISSUE THREAD

**Issue by hyhcrh** [nythepegasus/SideJITServer#53]
I sideloaded UTM (with JIT support, non-jailbreak version) via altstore.
I assure I configured the shortcut correctly.

Reproduce:
1. Configure SideJITServer and the shortcut as said in README.md.
2. Go to venv via 'source venv/bin/activate'
3. Execute 'sudo SideJITServer --pair'
4. Execute the shortcut, and select 'UTM SE' in the option.
5. The notification appeared.

What's strange is that the terminal output seems expected and no explicit error occured.
Please help.

Here is the console log:

<details>
Attempting to pair to a device! (Ctrl+C to stop)

[<PlistUsbmuxLockdownClient ID:0xxxxxx VERSION:17.3 TYPE:iPad14,3 PAIRED:True>]

Continue? [y/N]: y

INFO:     Started server process [15722]

INFO:     Waiting for application startup.

INFO:     Application startup complete.

INFO:     Uvicorn running on http://127.0.0.1:49151 (Press CTRL+C to quit)

INFO:     127.0.0.1:53985 - "GET / HTTP/1.1" 200 OK

Registration of service SideJITServer._http._tcp.local. in progress...

Service SideJITServer._http._tcp.local. registered

 * Serving Flask app 'SideJITServer'

 * Debug mode: off

INFO:werkzeug:WARNING: This is a development server. Do not use it in a production deployment. Use a production 
WSGI server instead.

 * Running on all addresses (0.0.0.0)

 * Running on http://127.0.0.1:8080

 * Running on http://192.168.10.9:8080

INFO:werkzeug:Press CTRL+C to quit

INFO:werkzeug:192.168.10.221 - - [24/May/2024 18:27:21] "GET /00xxxxx/ HTTP/1.1" 200 -

INFO:werkzeug:192.168.10.221 - - [24/May/2024 18:27:22] "GET /0xxxxxx/UTM/ HTTP/1.1" 200 -

</details>

**Comment by shijua** [comment]
same issue

**Comment by nythepegasus** [comment]
Hello, I'm unsure if SE supports JIT, but I recently tested UTM and it worked fine for me. UTM SE also seems to work. Try SideJITServer 1.3.2+
