### ISSUE TITLE
Internal Server Error

### ISSUE THREAD

**Issue by xanderuribe** [nythepegasus/SideJITServer#57]
After configuring everything for the shortcut, I pressed DolphiniOS and it loaded for a while, but then said this:

Internal Server Error
The server encountered an internal error and was unable to complete your request. Either the server is overloaded or there is an error in the application.

This is the error that I get in Powershell:

TimeoutError: [WinError 10060] A connection attempt failed because the connected party did not properly respond after a period of time, or established connection failed because connected host has failed to respond

**Comment by TheFervidActor** [comment]
did you find a solution?

**Comment by xanderuribe** [comment]
> did you find a solution?

I just tried it the next day

**Comment by matei1413** [comment]
xander, please close the issue
