### ISSUE TITLE
Help with simplifying these instructions:

### ISSUE THREAD

**Issue by RobThePCGuy** [nythepegasus/SideJITServer#59]
I wrote this up the best I could. I am on Windows. I have JIT working on my iPad Air 5th gen with the latest version of iOS installed. Please if this guide helps you may pick apart whatever you need. If not, trash it.

# Requirements:
- **Operating System:** Windows 11
- **Applications:** iTunes and iCloud applications directly from Apple (not from Microsoft Store).
- **Python Version:** Latest version (3.11.9 works for this setup). Use the following commands in PowerShell to verify:
  - `which python` to locate the Python installation.
  - `python --version` to check the installed Python version.

## Setting Up the Environment

1. **Launch PowerShell as an Administrator.**

2. Navigate to your Desktop:

    ```
    cd ~\Desktop
    ```
3. Clone the repository:

    ```
    git clone https://github.com/nythepegasus/SideJITServer.git
    ```
4. Change directory to the cloned repository and set up a Python virtual environment:

    ```
    cd ~\Desktop\SideJITServer
    python -m venv venv
    .\venv\Scripts\Activate.ps1
    ```
  You should now see: `(venv) PS` indicating that the virtual environment is activated.

5. Install required packages:

    ```
    pip install -r requirements.txt
    pip install SideJITServer
    ```
6. Check the installed version of SideJITServer:

    ```
    SideJITServer --version
    ```
  **Expected output:** `pymobiledevice3: 4.2.3` and `SideJITServer: 1.3.1`

7. Connect your iPad:
 - Plug in your iPad and wait for the 'Trust' prompt on the device.
 - It may help to sync the iPad with your computer first. Consider rebooting if things don’t behave as expected.

## Troubleshooting
- Ensure PowerShell is launched as Administrator.
- Navigate to the cloned repository directory.
- Activate the Python virtual environment.
- Run the `Activate.ps1` script.
- Install necessary packages and the server.
- Keep the iPad screen on at all times; do not let the screen lock.

## Pairing Devices

1. Pair the device:

     ```
     SideJITServer --pair
     ```
  The iPad will prompt with a 'Trust' window after running the command.

2. Verification:
  - On the iPad open the default browser and navigate to the third IP address provided by SideJITServer (e.g., `http://192.168.1.164:8080`). You should see a JSON response like:

      ```
      {"usbmux-########-################-USB":"########-################"}
      ```

3. Follow through:
  - Go to the [GitHub page](https://github.com/nythepegasus/SideJITServer), click on the [shortcut](https://www.icloud.com/shortcuts/b0ffc9c3f0e74e7a8f8052c89fa322cf) link, and enter the 25-character UDID found between `usbmux-` and `-USB`.
  - You'll need to give it the SideJITServer IP when prompted. (e.g., `http://192.168.1.164:8080`).
  - Save it and find 'All Shortcuts' on the left. Select the shortcut named 'SideJIT'.
  - Choose AltStore or another application to which you want to grant access.

**Comment by Bomen9** [comment]
After following all the steps correctly. 
After successful pairing, whenever I go to verify the device by navigating to the third IP address provided by SideJITServer (e.g., http://192.168.1.67:8080

The JSON response is - {ERROR":"Could not find device!"} #61

Please help.

**Comment by Pikmingaming9382** [comment]
Powershell wont let me do step two, it just says: 
`git: The term 'git' is not recognized as a name of a cmdlet, function, script file, or executable program.
Check the spelling of the name, or if a path was included, verify that the path is correct and try again.`
What do i do?

**Comment by dbacks2196** [comment]
@Gazerbeam2 Same here. Following this thread.
