### ISSUE TITLE
No Option for Folium

### ISSUE THREAD

**Issue by T4K4SHI** [nythepegasus/SideJITServer#6]
I have an app that needs JIT to run but for some reason it wont appear in my SideJIT Shortcut what do i do?![image](https://github.com/nythepegasus/SideJITServer/assets/166289799/23406b90-1509-4811-aa38-51187a57ec74)

**Comment by Montivillon** [comment]
Open this www.127.0.0.1:8080/re/ I faced the error too but I used it then refresh shortcuts and then run it and it work try it www.127.0.0.1:8080/re/   Please reply if it doesn’t work

**Comment by Montivillon** [comment]
Please reply

**Comment by WesleyBryie** [comment]
@T4K4SHI Another reason an app might not show up, is if it does not have the correct entitlements to be JIT-eligible.

**Comment by RoyalQX** [comment]
I was having this issue when I installed Folium through Esign with a distribution certificate. Once  I reinstalled with developer cert and refreshed SideJITServer, It showed up in the list and JIT was working.

**Comment by T4K4SHI** [comment]
> Please reply

Oh i fixed it i just had to reinstall folium

**Comment by takov751** [comment]
Nice,  in case of you have fixed it, it would be easier track from everyone to close issue as completed . 👍👍👍

**Comment by Montivillon** [comment]
Nice I just thought you side loaded with developer certificate

**Comment by LynetteCullens** [comment]
> Open this [www.127.0.0.1:8080/re/](http://www.127.0.0.1:8080/re/) I faced the error too but I used it then refresh shortcuts and then run it and it work try it [www.127.0.0.1:8080/re/](http://www.127.0.0.1:8080/re/) Please reply if it doesn’t work

The above suggestion worked for me.
