### ISSUE TITLE
Sideloaded Apps aren’t compatible/recognised by the shortcut.

### ISSUE THREAD

**Issue by SomewhatKai** [nythepegasus/SideJITServer#60]
So I used Maplesigner to turn an ipa file into an App, but the shortcut doesn’t let me enable the JIT for it. It only shows Altserver and that’s it. I think it’s because apps from Maplesigner aren’t connected to the Altserver.

**Comment by jwong5087** [comment]
Just use Altstore or altserver then

**Comment by PHIN1222** [comment]
Same issue here, surely there’s a way to get this to work to have permanently signed apps and easy jit access?

**Comment by nythepegasus** [comment]
They must be signed correctly with `get-task-allow`. If you use TrollStore, it has its own method of enabling JIT.
