### ISSUE TITLE
An attempt was made to access a socket in a way forbidden by its access permissions

### ISSUE THREAD

**Issue by michalcoonis** [nythepegasus/SideJITServer#66]
Hi, when running the script i get a following error: 
(venv) PS C:\Users\20231003\Desktop\SideJITServer-main> SideJITServer.exe
INFO:     Started server process [22816]
INFO:     Waiting for application startup.
INFO:     Application startup complete.
INFO:     Uvicorn running on http://127.0.0.1:49151 (Press CTRL+C to quit)
C:\Users\20231003\Desktop\SideJITServer-main\venv\Lib\site-packages\pymobiledevice3\utils.py:55: DeprecationWarning: There is no current event loop
  loop = asyncio.get_event_loop()
INFO:     127.0.0.1:58176 - "GET / HTTP/1.1" 200 OK
Registration of service SideJITServer._http._tcp.local. in progress...
Service SideJITServer._http._tcp.local. registered
 * Serving Flask app 'SideJITServer'
 * Debug mode: off
An attempt was made to access a socket in a way forbidden by its access permissions
Exception ignored in atexit callback: <bound method Zeroconf.unregister_service of <zeroconf._core.Zeroconf object at 0x000002249BDBBF50>>
Traceback (most recent call last):
  File "C:\Users\20231003\Desktop\SideJITServer-main\venv\Lib\site-packages\zeroconf\_core.py", line 455, in unregister_service
    run_coro_with_timeout(
  File "C:\Users\20231003\Desktop\SideJITServer-main\venv\Lib\site-packages\zeroconf\_utils\asyncio.py", line 117, in run_coro_with_timeout
    raise EventLoopBlocked from ex
zeroconf._exceptions.EventLoopBlocked:
sys:1: RuntimeWarning: coroutine 'Zeroconf.async_unregister_service' was never awaited
RuntimeWarning: Enable tracemalloc to get the object allocation traceback

First, i used the pair option with the same result.

**Comment by badphomet** [comment]
disable your vpn

**Comment by nythepegasus** [comment]
Ensure you're running as administrator on WiFi
