### ISSUE TITLE
‘NoneType’ object has no attribute ‘address’

### ISSUE THREAD

**Issue by Pandaprogaming** [nythepegasus/SideJITServer#67]
So I did everything and when I run sidejitserver after I paid my device it gives this error “ ‘NoneType’ object has no attribute ‘address’” and idk why here’s a screenshot
![image](https://github.com/nythepegasus/SideJITServer/assets/98915070/cbd3f5f9-40db-4878-bee6-5d4e20ce202e)

**Comment by Bomen9** [comment]
Please share complete process.

**Comment by Pandaprogaming** [comment]
Well I did how I did it before and now randomly I get this error I install the files from GitHub then extract it and install venv in that folder and I install all requirements 
Finally I install SideJITServer and run SideJITServer -y that works then I start SideJITServer and that's when I get the message

**Comment by Pandaprogaming** [comment]
Also I'm running on Ubuntu

**Comment by tml89** [comment]
Found you a solution? Got the same error

**Comment by nythepegasus** [comment]
Could you try the latest version? If not I will look into this further

**Comment by Pandaprogaming** [comment]
> Could you try the latest version? If not I will look into this further

Same thing
