### ISSUE TITLE
Conversion error on iOS 18 Beta

### ISSUE THREAD

**Issue by serega2004** [nythepegasus/SideJITServer#69]
When I run the shortcut on iOS 18 Beta, it shows the following error:
"Get Contents of dictionary failed because Shortcuts couldn't convert Rich text to dictionary."
Will there be a fix?

**Comment by serega2004** [comment]
This error is back

**Comment by nythepegasus** [comment]
Ensure you put the correct URL in, or try using SideStore nightly's current integration.
