### ISSUE TITLE
error code 400

### ISSUE THREAD

**Issue by NepsAndHelis** [nythepegasus/SideJITServer#7]
![Screenshot (2)](https://github.com/nythepegasus/SideJITServer/assets/134784243/d4ec4e0f-4bcf-49dc-a939-c8a7a1b8a96d)
Im running on windows 11
Powershell as admin 
followed the video instructions found here https://www.youtube.com/watch?v=EM3CPA3kRIA
keep on getting stuck at the error shown
rebooted, didnt work
disabled windows firewall, didnt work

**Comment by Montivillon** [comment]
Refresh? Go to this link and try again but make sure you open the link in the computer www.127.0.0.1:8080/re/

**Comment by pixeles3ds** [comment]
I got the same error, I put by mistake in the shorcut setup: ( https://*** ), it must be ( http://*** )
