### ISSUE TITLE
Windows Powershell Error “ObjectNotFound: (pip3: String) [], CommandNotFoundException

### ISSUE THREAD

**Issue by Rayman1995** [nythepegasus/SideJITServer#70]
![image](https://github.com/nythepegasus/SideJITServer/assets/167638976/6f4772d0-73fb-454f-adc1-de4c00179c5a)
How to fix this? I tried 4 times, but still not working, i using a Windows 10 and a IPhone SE (IOS 17.4.1)

**Comment by nythepegasus** [comment]
Make sure you have Python installed
