### ISSUE TITLE
Cannot start the web server

### ISSUE THREAD

**Issue by Tama47** [nythepegasus/SideJITServer#71]
```
Continue? [y/N]: yes
INFO:     Started server process [15255]
INFO:     Waiting for application startup.
INFO:     Application startup complete.
ERROR:    [Errno 48] error while attempting to bind on address ('127.0.0.1', 49151): address already in use
INFO:     Waiting for application shutdown.
INFO:     Application shutdown complete.
/Users/tama/venv/lib/python3.12/site-packages/pymobiledevice3/utils.py:55: DeprecationWarning: There is no current event loop
  loop = asyncio.get_event_loop()
```

**Comment by SRS026** [comment]
Got the exact same error on macOS Sonoma.

My iPhone is currently running on iOS18 Developer Beta.

**Comment by artchsh** [comment]
This error means that this port is already used by some program
I would recommend firstly restarting your computer, and trying again.
If this did not help, follow these steps:
1. Use this command, to find id of proccess, that uses that port 
`lsof -i:49151`
The output will be:
```
COMMAND   PID    USER   FD   TYPE             DEVICE SIZE/OFF NODE NAME
Python  57501   admin   49u  IPv4 0x401031a75c4ec941      0t0  TCP localhost:49151 (LISTEN)
```

2. Then you need to kill this proccess, by using `kill` and providing PID
`sudo kill -9 57501`

After following these steps, there should be no error when you executing `SideJITServer --pair`

If same problem occurs again, repeat.

**Comment by SRS026** [comment]
Thank you for your reply - Your solution resolved **ERROR:    [Errno 48] error while attempting to bind on address ('127.0.0.1', 49151): address already in use**

Much appreciated 👍 

Unfortunately the server error still remains. Noticed this is being reported by others too.

Followed Nythepegasus SideJITServer tutorial on YouTube - The same issue occurs on both Windows and macOS attempts:

INFO:     Uvicorn running on http://127.0.0.1:49151 (Press CTRL+C to quit)
C:\Users\Stu\AppData\Local\Programs\Python\Python312\Lib\site-packages\pymobiledevice3\utils.py:55: DeprecationWarning: There is no current event loop
  loop = asyncio.get_event_loop()

**Comment by nythepegasus** [comment]
Ensure you only have 1 SideJITServer running and try the latest version. Sometimes the tunnel doesn't close so you'll have to find it in Task Manager/Activity Monitor/btop. Definitely need to polish tunnel management more
