### ISSUE TITLE
WINDOWS tunneld issues cannot find device (ios18)

### ISSUE THREAD

**Issue by JD9871** [nythepegasus/SideJITServer#73]
![image](https://github.com/nythepegasus/SideJITServer/assets/164794137/fb864777-af2d-4dfb-9ff7-095abdb8b393)![image](https://github.com/nythepegasus/SideJITServer/assets/164794137/ae96b6f9-5163-46af-969a-602601de5a75)![image](https://github.com/nythepegasus/SideJITServer/assets/164794137/211345ca-b3af-45b0-9149-8e822ff4272c)

Did the install and everything. I know iOS 18 is beta build but I've seen several people post working versions. Followed the GitHub guide and verified all my installed files are there after the pip3 install command. Can't start tunneld seems to be the main issue. Any help would be appreciated

**Comment by eliadwe** [comment]
I have the same issue (Also on IOS18 Beta)
