### ISSUE TITLE
SideJITServer on a Linux machine?

### ISSUE THREAD

**Issue by econcz** [nythepegasus/SideJITServer#78]
Is there any way to run the SideJITServer on a Linux machine? It seems that a protocol is missing, but which one, apple_p2p? Is there any Linux solution for it? Thank you!

raspberrypi# SideJITServer -v 
INFO:     Started server process [196]
INFO:     Waiting for application startup.
INFO:     Application startup complete.
INFO:     Uvicorn running on http://127.0.0.1:49151 (Press CTRL+C to quit)
INFO:     127.0.0.1:36732 - "GET / HTTP/1.1" 200 OK
Traceback (most recent call last):
  File "/usr/local/bin/SideJITServer", line 8, in <module>
    sys.exit(start_server())
             ^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/dist-packages/click/core.py", line 1157, in __call__
    return self.main(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/dist-packages/click/core.py", line 1078, in main
    rv = self.invoke(ctx)
         ^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/dist-packages/click/core.py", line 1434, in invoke
    return ctx.invoke(self.callback, **ctx.params)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/dist-packages/click/core.py", line 783, in invoke
    return __callback(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/dist-packages/SideJITServer/__init__.py", line 253, in start_server
    create_service()
  File "/usr/local/lib/python3.11/dist-packages/SideJITServer/__init__.py", line 200, in create_service
    zeroconf = Zeroconf()
               ^^^^^^^^^^
  File "/usr/local/lib/python3.11/dist-packages/zeroconf/_core.py", line 180, in __init__
    listen_socket, respond_sockets = create_sockets(interfaces, unicast, ip_version, apple_p2p=apple_p2p)
                                     ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/dist-packages/zeroconf/_utils/net.py", line 374, in create_sockets
    respond_socket = new_respond_socket(i, apple_p2p=apple_p2p)
                     ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/dist-packages/zeroconf/_utils/net.py", line 343, in new_respond_socket
    respond_socket.setsockopt(
OSError: [Errno 92] Protocol not available

**Comment by econcz** [comment]
Apologies, the described protocol error is a known zeroconf problem under Docker, which, according to the wisdom of the internet, nobody has tackled yet. It reproduces itself under most distributions in a container.

Here is a script, which installs all dependencies (please, mind the python3.11 - I'm suing Raspbian Bullseye) and is able to launch SideJITServer on Raspberry Pi, but it ends up in a tunnel exception after one clicks 'y' after sidejitserver --pair, and no 

#!/bin/bash

[[ "$(dpkg -l | grep usbmuxd)" == ""                                       ]] &&
{ sudo apt update                                                            ;
  sudo apt install -y libsqlite3-dev libplist3 usbmuxd                       ; }
[[ "$(python3.11 -V 2> /dev/null)" == "" || $@ == *"--reinstall"           ]] &&
{ cd /tmp/ && wget https://www.python.org/ftp/python/3.11.9/Python-3.11.9.tgz;
  tar -xzvf Python-3.11.9.tgz                                                ;
  cd Python-3.11.9/                                                          ;
  ./configure --enable-loadable-sqlite-extensions --enable-optimizations     ;
  sudo make altinstall                                                       ;
  echo "installation complete, please run the script again!"         ; exit 0; }
[[ "$(python3.11 -V 2> /dev/null)" != "" && $@ == *"--update"              ]] &&
python3.11 -m pip install --no-cache-dir --upgrade SideJITServer

sudo usbmuxd -u $(whoami)                                      &> /dev/null
SideJITServer "$@"

**Comment by econcz** [comment]
Solved. SideJITServer must be installed from root (via "sudo pip3" ...).
The following script configures and starts SideJITServer on Raspberry Pi Debian 11 Bullseye, but will work on any Linux machine with Debian/Ubuntu. One only needs to plugin iPhone/iPad into the Pi and launch it. Happy using!

PS You can modify the script as you like

#!/bin/zsh

# SideJITServer (libplist3, usbmuxd, python3.11)
[[ "$(dpkg -l | grep usbmuxd)" == ""                                       ]] &&
{ sudo apt update                                                            ;
  sudo apt install -y libsqlite3-dev libplist3 usbmuxd                       ; }
[[ "$(python3.11 -V 2> /dev/null)" == "" || $@ == *"--reinstall"           ]] &&
{ cd /tmp/ && wget https://www.python.org/ftp/python/3.11.9/Python-3.11.9.tgz;
  tar -xzvf Python-3.11.9.tgz                                                ;
  cd Python-3.11.9/                                                          ;
  ./configure --enable-loadable-sqlite-extensions --enable-optimizations     ;
  sudo make altinstall; sudo apt reinstall python3-pip                       ;
  echo "installation complete, please run the script again!"         ; exit 0; }
####
[[ "$(python3.11 -V 2> /dev/null)" != "" && $@ == *"--upgrade"             ]] &&
sudo python3.11 -m pip install --no-cache-dir --upgrade SideJITServer
####
sudo usbmuxd --exit                                            &> /dev/null
sudo usbmuxd                                                   &> /dev/null
sudo SideJITServer "$@"

####
####

**Comment by econcz** [comment]
A version of the script compatible with Debian 12 and Ubuntu 22:

```
#!/bin/zsh

# SideJITServer (libplist3, usbmuxd, python3.11)
[[ "$(dpkg -l | grep usbmuxd)" == ""                                       ]] &&
{ sudo apt update                                                            ;
  sudo apt install -y libplist3 usbmuxd                                      ; }
[[ $(python3 --version | sed -E -e 's/[^0-9]//g') -lt 3110                 ]] &&
{ cd /tmp/ && wget https://www.python.org/ftp/python/3.11.9/Python-3.11.9.tgz;
  tar -xzvf Python-3.11.9.tgz                                                ;
  cd Python-3.11.9/                                                          ;
  ./configure --enable-loadable-sqlite-extensions --enable-optimizations     ;
  sudo make altinstall; sudo apt reinstall python3-pip                       ;
  echo "installation complete, please run the script again!"         ; exit 0; }
####
[[ $(python3 --version | sed -E -e 's/[^0-9]//g') -lt 3110                 ]] &&
sudo python3.11 -m pip install --no-cache-dir --upgrade SideJITServer         ||
[[ $(which SideJITServer)                          ==   ""                 ]] &&
{ sudo apt update                                                            ;
  sudo apt install pipx                                                      ;
  pipx reinstall SideJITServer                                               ; }
####
sudo usbmuxd --exit                                            &> /dev/null
sudo usbmuxd                                                   &> /dev/null
sudo "$(which SideJITServer)" "$@"

####
####
```

**Comment by nythepegasus** [comment]
Also make sure to try using the current latest version, as well as running as sudo
