### ISSUE TITLE
SideJITServer without USB?

### ISSUE THREAD

**Issue by Blockmaster2706** [nythepegasus/SideJITServer#79]
So I'm wondering, since I would like to try deploying SideJITServer to a cloud vm, would it be possible to do this despite no way to connect USB?

Why exactly is the USB Connection necessary to pair in the first place? Does it need to pull specific info to a file? If so, would it be possible to do the pairing on one device, and then copy the file to another?

I would be able to use Tailscale to make sure the ip address I need to input does not change between pairing and deploying, if that helps. 

Thanks in advance

**Comment by fish4terrisa-MSDSM** [comment]
Maybe you can try USB/IP? ( I'll try it later..)

**Comment by nythepegasus** [comment]
It should work after the initial pairing over USB. Try using the current latest version
