### ISSUE TITLE
idk how to fix this but sideJITserver gave me a error that said

### ISSUE THREAD

**Issue by Samuel525432** [nythepegasus/SideJITServer#81]
{"ERROR":"Could not find device!"}

**Comment by WillamSun** [comment]
Any futher info from the console? And also try change a carble.

**Comment by Samuel525432** [comment]
What does Carble mean exactly 
I mean like what does Carble means exactly

**Comment by WillamSun** [comment]
> What does Carble mean exactly I mean like what does Carble means exactly

Sorry that's a typo. i mean cable

**Comment by Samuel525432** [comment]
You’re good some people make typos all the time 
But my MacBook Air doesn’t support USB connection so yeah

**Comment by WillamSun** [comment]
> You’re good some people make typos all the time 
> 
> But my MacBook Air doesn’t support USB connection so yeah

Can u provide the console output?

**Comment by Samuel525432** [comment]
UTM SE is now in the App Store I’m not lying get it while is still hot
https://apps.apple.com/us/app/utm-se-retro-pc-emulator/id1564628856

**Comment by nythepegasus** [comment]
Could you try using the newest version?
