### ISSUE TITLE
PyWinTunException(f"Failed to create adapter. Last error: {last_error.value}")

### ISSUE THREAD

**Issue by ixon8** [nythepegasus/SideJITServer#84]
SideJITServer starts up fine, but as soon as i connect the phone through usb, it throws this error
File "C:\Users\exii\Desktop\ios\SideJITServer-1.3.1\venv\Lib\site-packages\pytun_pmd3\wintun.py", line 206, in __init__
    raise PyWinTunException(f"Failed to create adapter. Last error: {last_error.value}")
pytun_pmd3.exceptions.PyWinTunException: Failed to create adapter. Last error: 0

**Comment by ixon8** [comment]
and if i try to use the shortcut, it just says Could not find device error

**Comment by RestytheCake** [comment]
run as admin
