### ISSUE TITLE
No such service: com.apple.instruments.dtservicehub

### ISSUE THREAD

**Issue by harryxhk** [nythepegasus/SideJITServer#85]
Device: iOS 18 Beta 3; Windows 11
The shortcut gave a notification "Internal server error", and the sidejitserver showed "No such service: com.apple.instruments.dtservicehub"
![image](https://github.com/user-attachments/assets/6f445b73-0661-46e3-96a6-246febb45ec7)

Already in a virtual envirnment, turned on the developer mode on ios and running with an adminstrator priviledge.

**Comment by harryxhk** [comment]
uhmm in this picture the venv is not activated. but the same problem remains while it is activated.
![image](https://github.com/user-attachments/assets/8b11212d-a667-45f1-bcd5-2c06964f156c)

**Comment by buglinjo** [comment]
Following! Same issue on IOS 18.1 Beta

**Comment by doronz88** [comment]
Verify with pymobile instead of sidjitserver.
First verify Dev mode:
```shell
pymobiledevice3 amfi developer-mode-status
```
Then, try starting tunneld and accessing dvt:
```shell
sudo pymobiledevice3 remote tunneld
pymobiledevice3 developer dvt ls /
```

**Comment by buglinjo** [comment]
> Verify with pymobile instead of sidjitserver. First verify Dev mode:
> 
> ```shell
> pymobiledevice3 amfi developer-mode-status
> ```
> 
> Then, try starting tunneld and accessing dvt:
> 
> ```shell
> sudo pymobiledevice3 remote tunneld
> pymobiledevice3 developer dvt ls /
> ```

Here's the output I get...
![image](https://github.com/user-attachments/assets/9d9ab840-a2d3-4a1c-b7f4-3be4891814be)
![image](https://github.com/user-attachments/assets/b662ce26-abd8-42f7-b8ab-508bdb063c14)

**Comment by doronz88** [comment]
All good then. The DVT answers as it should. This means the bug only exists on SideJITServer. Maybe due to it not supporting latest pymobile version

**Comment by nythepegasus** [comment]
Hopefully my updating has fixed this issue, but if not definitely reopen this issue.
