### ISSUE TITLE
Error could not find device (after first pair)

### ISSUE THREAD

**Issue by 007Ace0007** [nythepegasus/SideJITServer#87]
So I got JIT working yesterday with dolphin iOS then I closed the server but when I reopened it and tried to launch it again I got the couldn’t find device error which lead me having to re-pair my phone to the server via cable. Now the next day I’ve relaunched the server getting the same cannot find device. Do I have to re-pair every time I want to use JIT? I will also attach a image of what is coming up in the console 
![IMG_2033](https://github.com/user-attachments/assets/b5e4ce91-d0a1-46ee-8d25-281f5031d56d)

**Comment by xroneios** [comment]
Same do u find how to fix?

**Comment by 007Ace0007** [comment]
> Same do u find how to fix?

Nope. Just gave up was trying to use it for dolphin. Might go back to android heard you can even run a switch emulator on new androids

**Comment by nythepegasus** [comment]
Could you try using the latest version? If not, Android isn't too terrible.
