### ISSUE TITLE
Shortcut says “The request is timed out”

### ISSUE THREAD

**Issue by Cnypu** [nythepegasus/SideJITServer#89]
When I run my shortcut it stops at “Get contents of server/UDID” and then says “The request timed out”
What can I do with it? I follow tutorials correctly
My phone is iPhone 15 with iOS 17.4.1
![IMG_0211](https://github.com/user-attachments/assets/4267db42-6316-49a0-850c-fc5416308487)
![IMG_0212](https://github.com/user-attachments/assets/13610edd-2231-4f13-b904-8124a35d7c1b)

**Comment by SkywalkerIron** [comment]
check your udid and server ip
maybe they are not in the same network or the udid and ip is wrong

**Comment by Cnypu** [comment]
Worked at other PC and everything is ok
