### ISSUE TITLE
 downgraded pymobiledevice3 to 3.0.3 and i got error code 200 and it could not find device

### ISSUE THREAD

**Issue by IMTHECOOLEST** [nythepegasus/SideJITServer#9]
just read the title
![Screenshot 2024-04-09 133304](https://github.com/nythepegasus/SideJITServer/assets/147947889/3ea20296-bee3-4b86-b491-ac62d89e6919)

**Comment by Montivillon** [comment]
I never got that error but before I used SideJITServer, I downgrade pymobiledevice3 to 2.30.0 or check the AltStore docs but that’s the most compatible version for it to work try downgrading

**Comment by Montivillon** [comment]
If you downgraded and still did not work, refresh the server with this linked, I open and it work www.127.0.0.1:8080/re/

**Comment by stossy11** [comment]
1. 200 is not a error

**Comment by stossy11** [comment]
2. try the latest version of SideJITServer and make sure to pair your device with SideJITServer -y
