### ISSUE TITLE
SideJITServer couldn't find Play! when enabling JIT

### ISSUE THREAD

**Issue by tristafae** [nythepegasus/SideJITServer#90]
![image](https://github.com/user-attachments/assets/3680950f-254b-47fc-8cdd-2e46b477cada)
The title really explains it all and this is really all I get. I know I've set SideJITServer up correctly as it worked previously with Dolphinios. Idk what's up. Thanks!

Edit: 
This is all I get on my computer's side
`INFO:werkzeug:192.168.1.87 - - [19/Jul/2024 10:00:27] "GET /00008020-00110D363CFA002E/Play/ HTTP/1.1" 200 -`

**Comment by nythepegasus** [comment]
Closing in favor of #27
