### ISSUE TITLE
Finally I setup pc to make server work but 

### ISSUE THREAD

**Issue by Yen0928** [nythepegasus/SideJITServer#98]
![IMG_0005](https://github.com/user-attachments/assets/5338ae0d-1783-40ca-9577-9b2ccf3cd5a8)
Finally I setup pc to make server work but 

last step error

SideJIT

Internal Server Error
The server encountered an internal error and was unable to complete your request. Either the server is overloaded or there is an error in the application.

Help me please

M4 iPad Pro

**Comment by nythepegasus** [comment]
Ensure you input the correct URL. Other issues also reference this, unsure of their numbers
