### ISSUE TITLE
ERROR: Could not find device

### ISSUE THREAD

**Issue by NintendoNerdWasTaken** [nythepegasus/SideJITServer#99]
Hello, I am using iOS 17.0.3 on an iPhone XR. I keep getting this error whenever I try to run the SideJIT shortcut on my phone. I made sure that my UDID and IP matched, opened iTunes in the background and repairing my phone with my PC, but to no avail. Has anyone found a fix for this yet?

**Comment by xroneios** [comment]
Same

**Comment by nythepegasus** [comment]
Closing in favor of #111
